# Minimal configuration example
# Uses environment variable NGROK_API_KEY for authentication

agent:
  region: "us"

endpoints:
  - name: "my-app"
    uri: "https://my-app.ngrok.app"
    local_port: 8080
