# ngrokd Daemon Configuration
# This is the default configuration for ngrokd daemon mode

# ngrok API configuration
api:
  url: https://api.ngrok.com
  key: ""  # Set via: ngrok daemon set-api-key <KEY>
           # Or set NGROK_API_KEY environment variable

# Ingress endpoint (usually auto-detected)
ingressEndpoint: "kubernetes-binding-ingress.ngrok.io:443"

# Server settings
server:
  log_level: info           # Options: info, debug, error
  socket_path: /var/run/ngrokd.sock
  client_cert: /etc/ngrokd/tls.crt
  client_key: /etc/ngrokd/tls.key

# Bound endpoints polling configuration
bound_endpoints:
  poll_interval: 30         # Seconds between API polls
  selectors: ['true']       # Endpoint selectors (currently unused)

# Network configuration
net:
  interface_name: ngrokd0      # Virtual interface name
  subnet: 10.107.0.0/16        # IP subnet (Linux: 10.107.x, macOS: auto 127.0.0.x)
  network_accessible: false    # Set true to bind 0.0.0.0 for network access
  start_port: 9080             # Starting port for network listeners (if enabled)
