//go:build linux

package dns

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-logr/logr"
)

func TestResolvManager_ParseUpstreamServers(t *testing.T) {
	dir := t.TempDir()
	resolvPath := filepath.Join(dir, "resolv.conf")

	content := `# This is a comment
nameserver 10.0.0.1
nameserver 10.0.0.2
search example.com
nameserver 8.8.8.8
`
	if err := os.WriteFile(resolvPath, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	m := NewResolvManagerWithPaths(resolvPath, filepath.Join(dir, "backup"), logr.Discard())
	servers, err := m.ParseUpstreamServers()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expected := []string{"10.0.0.1:53", "10.0.0.2:53", "8.8.8.8:53"}
	if len(servers) != len(expected) {
		t.Fatalf("expected %d servers, got %d: %v", len(expected), len(servers), servers)
	}
	for i, s := range servers {
		if s != expected[i] {
			t.Fatalf("server[%d]: expected %s, got %s", i, expected[i], s)
		}
	}
}

func TestResolvManager_ManageAndRestore(t *testing.T) {
	dir := t.TempDir()
	resolvPath := filepath.Join(dir, "resolv.conf")
	backupDir := filepath.Join(dir, "backup")

	original := "nameserver 10.0.0.1\nnameserver 10.0.0.2\n"
	if err := os.WriteFile(resolvPath, []byte(original), 0644); err != nil {
		t.Fatal(err)
	}

	m := NewResolvManagerWithPaths(resolvPath, backupDir, logr.Discard())

	if err := m.ManageResolvConf("127.0.0.1:53"); err != nil {
		t.Fatalf("ManageResolvConf: %v", err)
	}

	data, err := os.ReadFile(resolvPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "nameserver 127.0.0.1") {
		t.Fatalf("resolv.conf should contain our nameserver, got: %s", data)
	}
	// Original nameservers should be preserved (prepend mode)
	if !strings.Contains(string(data), "10.0.0.1") {
		t.Fatalf("resolv.conf should still contain original nameserver, got: %s", data)
	}

	backupPath := filepath.Join(backupDir, backupFileName)
	backupData, err := os.ReadFile(backupPath)
	if err != nil {
		t.Fatalf("backup not found: %v", err)
	}
	if string(backupData) != original {
		t.Fatalf("backup content mismatch: got %q, want %q", backupData, original)
	}

	if err := m.RestoreResolvConf(); err != nil {
		t.Fatalf("RestoreResolvConf: %v", err)
	}

	data, err = os.ReadFile(resolvPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != original {
		t.Fatalf("after restore: got %q, want %q", data, original)
	}

	if _, err := os.Stat(backupPath); !os.IsNotExist(err) {
		t.Fatal("backup file should be removed after restore")
	}
}

func TestResolvManager_CrashRecovery(t *testing.T) {
	dir := t.TempDir()
	resolvPath := filepath.Join(dir, "resolv.conf")
	backupDir := filepath.Join(dir, "backup")

	original := "nameserver 192.168.1.1\n"
	managed := "# Generated by ngrokd - do not edit\nnameserver 127.0.0.1\n"

	os.MkdirAll(backupDir, 0755)
	os.WriteFile(resolvPath, []byte(managed), 0644)
	os.WriteFile(filepath.Join(backupDir, backupFileName), []byte(original), 0644)

	m := NewResolvManagerWithPaths(resolvPath, backupDir, logr.Discard())
	if err := m.RecoverFromCrash(); err != nil {
		t.Fatalf("RecoverFromCrash: %v", err)
	}

	data, err := os.ReadFile(resolvPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != original {
		t.Fatalf("after crash recovery: got %q, want %q", data, original)
	}
}

func TestResolvManager_NoCrashRecoveryNeeded(t *testing.T) {
	dir := t.TempDir()
	resolvPath := filepath.Join(dir, "resolv.conf")

	original := "nameserver 8.8.8.8\n"
	os.WriteFile(resolvPath, []byte(original), 0644)

	m := NewResolvManagerWithPaths(resolvPath, filepath.Join(dir, "backup"), logr.Discard())
	if err := m.RecoverFromCrash(); err != nil {
		t.Fatalf("RecoverFromCrash: %v", err)
	}

	data, _ := os.ReadFile(resolvPath)
	if string(data) != original {
		t.Fatalf("resolv.conf should be unchanged: got %q", data)
	}
}

func TestResolvManager_RestoreWithNoBackup(t *testing.T) {
	dir := t.TempDir()
	m := NewResolvManagerWithPaths(
		filepath.Join(dir, "resolv.conf"),
		filepath.Join(dir, "backup"),
		logr.Discard(),
	)
	if err := m.RestoreResolvConf(); err != nil {
		t.Fatalf("RestoreResolvConf with no backup should not error: %v", err)
	}
}

func TestResolvManager_AddDomainAutoManages(t *testing.T) {
	dir := t.TempDir()
	resolvPath := filepath.Join(dir, "resolv.conf")
	backupDir := filepath.Join(dir, "backup")

	original := "nameserver 10.0.0.1\n"
	if err := os.WriteFile(resolvPath, []byte(original), 0644); err != nil {
		t.Fatal(err)
	}

	m := NewResolvManagerWithPaths(resolvPath, backupDir, logr.Discard())

	// First AddDomain should auto-manage resolv.conf
	if err := m.AddDomain("example.com", "127.0.0.2:53"); err != nil {
		t.Fatalf("AddDomain: %v", err)
	}

	data, err := os.ReadFile(resolvPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "nameserver 127.0.0.2") {
		t.Fatalf("resolv.conf should contain our nameserver after AddDomain, got: %s", data)
	}
	if !strings.Contains(string(data), "ngrokd managed") {
		t.Fatalf("resolv.conf should contain managed marker, got: %s", data)
	}

	// Verify backup was created
	backupData, err := os.ReadFile(filepath.Join(backupDir, backupFileName))
	if err != nil {
		t.Fatalf("backup should exist after AddDomain: %v", err)
	}
	if string(backupData) != original {
		t.Fatalf("backup mismatch: got %q, want %q", backupData, original)
	}

	// Second AddDomain should be a no-op (already managed)
	if err := m.AddDomain("other.com", "127.0.0.2:53"); err != nil {
		t.Fatalf("second AddDomain: %v", err)
	}

	data2, _ := os.ReadFile(resolvPath)
	if string(data2) != string(data) {
		t.Fatalf("resolv.conf should not change on second AddDomain")
	}

	// Restore should work
	if err := m.RestoreResolvConf(); err != nil {
		t.Fatalf("RestoreResolvConf: %v", err)
	}
	restored, _ := os.ReadFile(resolvPath)
	if string(restored) != original {
		t.Fatalf("after restore: got %q, want %q", restored, original)
	}
}

func TestResolvManager_AddDomainSkipsIfAlreadyManaged(t *testing.T) {
	dir := t.TempDir()
	resolvPath := filepath.Join(dir, "resolv.conf")
	backupDir := filepath.Join(dir, "backup")

	original := "nameserver 10.0.0.1\n"
	os.WriteFile(resolvPath, []byte(original), 0644)

	m := NewResolvManagerWithPaths(resolvPath, backupDir, logr.Discard())

	// Manually manage first
	if err := m.ManageResolvConf("127.0.0.2:53"); err != nil {
		t.Fatalf("ManageResolvConf: %v", err)
	}
	afterManage, _ := os.ReadFile(resolvPath)

	// AddDomain should not modify resolv.conf again
	if err := m.AddDomain("example.com", "127.0.0.2:53"); err != nil {
		t.Fatalf("AddDomain: %v", err)
	}
	afterAdd, _ := os.ReadFile(resolvPath)
	if string(afterAdd) != string(afterManage) {
		t.Fatalf("AddDomain should not modify already-managed resolv.conf")
	}
}

func TestResolvManager_IsSymlink(t *testing.T) {
	dir := t.TempDir()
	realPath := filepath.Join(dir, "real.conf")
	linkPath := filepath.Join(dir, "resolv.conf")

	os.WriteFile(realPath, []byte("nameserver 1.1.1.1\n"), 0644)
	os.Symlink(realPath, linkPath)

	m := NewResolvManagerWithPaths(linkPath, filepath.Join(dir, "backup"), logr.Discard())
	if !m.IsSymlink() {
		t.Fatal("expected IsSymlink=true for symlinked resolv.conf")
	}

	m2 := NewResolvManagerWithPaths(realPath, filepath.Join(dir, "backup"), logr.Discard())
	if m2.IsSymlink() {
		t.Fatal("expected IsSymlink=false for regular file")
	}
}
